# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cricket < Formula
  desc ""
  homepage "https://github.com/timwmillard/homebrew-tap"
  version "0.1.3-next"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/timwmillard/cricket/releases/download/v0.1.2/cricket_Mac_intel.tar.gz"
      sha256 "4e4be13fd45028486dfbc52aac19b26b33ee5b85778d7417d7aadc57c6acdf09"

      def install
        bin.install "cricket"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/timwmillard/cricket/releases/download/v0.1.2/cricket_Mac_m1.tar.gz"
      sha256 "9fe0b7344993386f05eb42fc811a61d9d994ba6cfa485963e71ef578d3361ddb"

      def install
        bin.install "cricket"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/timwmillard/cricket/releases/download/v0.1.2/cricket_Linux_arm64.tar.gz"
      sha256 "3a5abac64511cc69425b01fedde508374c5eb955bbe76ea4b7d9ad74010c3c89"

      def install
        bin.install "cricket"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/timwmillard/cricket/releases/download/v0.1.2/cricket_Linux_x86_64.tar.gz"
      sha256 "faa15d868aca5e4893dd3dcb1c275ef28461e62f2f798f377722e87434da2d8b"

      def install
        bin.install "cricket"
      end
    end
  end
end
