# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cricket < Formula
  desc "Convert MyCricket results to a text format."
  homepage "https://github.com/timwmillard/homebrew-tap"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/timwmillard/cricket/releases/download/v0.1.3/cricket_Mac_m1.tar.gz"
      sha256 "ab43550b9aae187ae6468d2d8b457aa6ff182fe2d5cf4c9bdf28871be3f3987e"

      def install
        bin.install "cricket"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/timwmillard/cricket/releases/download/v0.1.3/cricket_Mac_intel.tar.gz"
      sha256 "799f1bb114b7b9648226ba3d85658cd868657d64e34bc982bf3f9e245a42b795"

      def install
        bin.install "cricket"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/timwmillard/cricket/releases/download/v0.1.3/cricket_Linux_arm64.tar.gz"
      sha256 "f8fd4f8fac8b4011338214c19a8f78d20404b3ebf6f48192e93bc47c52064da1"

      def install
        bin.install "cricket"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/timwmillard/cricket/releases/download/v0.1.3/cricket_Linux_x86_64.tar.gz"
      sha256 "8a4d81cb72087e80ac5797dafb9b88ea23d973c87e8af25e8f02d5a05562cac7"

      def install
        bin.install "cricket"
      end
    end
  end
end
